### ISSUE TITLE
wss support

### ISSUE THREAD

**Issue by fredericmalo** [fatedier/frp#2119]
**The solution you want**

Hello, as I don't understand chinese, could someone explain the status of this  pull request ? It seems that it solves my issue

https://github.com/fatedier/frp/pull/1919

As Caddy Server provides wss support out-of-the-box (I didn't need any configuration on this), I would need ro reverse proxy https + wss with FRP. For now, wss are in 'pending' mode in Chrome. 

**Alternatives considered**

I don't think there is any alternative, but please explain how to configure rpc for this !

Thanks !

**Comment by fatedier** [comment]
It won't be supported since the protocol is between frpc and frps.

What's your usage scenario?

**Comment by fredericmalo** [comment]
Dear, 

I was using Caddy server to handle http/https requests, but it exposes the public IP of my home router. I would like to hide my public IP by tunneling thanks to FRP.

I would like to expose a Node-Red instance through FRP, but the wss flow stays in "pending" status. 
As explained [here](https://discourse.nodered.org/t/websocket-connection-handshake-404-on-comms-nginx-to-node-red-does-block-websocket-communication/15619), node-red needs wss://domain.ltd/comms to push real-time debug messages to the webinterface:

<img width="676" alt="wss - domain ltd - comms" src="https://user-images.githubusercontent.com/3525134/100627571-73888500-3327-11eb-8df2-1c20f240d86c.png">

As wss is quiet popular protocol now, I guess it would interest lots of FRP users :)
 
It works out-of-the-box with Caddyfile with this config: 
```
nodered.mydomain.com {
  log {
    output file /logs/nodered.log
  }
  reverse_proxy localhost:1880
}
```

Do you need more clarification from my side ? 

Thanks, best !

**Comment by fatedier** [comment]
Follow these documents:

https://github.com/fatedier/frp#visit-your-web-service-in-lan-by-custom-domains

https://github.com/fatedier/frp#enable-https-for-local-http-service

Or just use `TCP` type https://github.com/fatedier/frp#access-your-computer-in-lan-by-ssh

**Comment by fewkso** [comment]
Hi @fatedier, our frps is behind a https load balancer which forces http to https, so we can't use insecure websocket connection. The proposed change is simple and it works (could it be refined?, maybe, I don't know), but it would super useful to have the feature out of the box instead of having to merge the code ourself.

**Comment by fatedier** [comment]
@fewkso You problem isn't same here.

 It's not the protocol we want to support between frpc and frps. It will limit the original design for frp's self protocol.

You can try to combine frps with other tunnel projects which can tunnel TCP on other protocols like websocket or UDP.

**Comment by fredericmalo** [comment]
Hello, I digg into this issue and found that websocket are working properly in http mode: 

```
[nodered-http]
type = http
local_ip = my-server-ip
local_port = 1880
custom_domains = nodered.mydomain.com
```
<img width="888" alt="ws" src="https://user-images.githubusercontent.com/3525134/101511554-f4c0c700-397a-11eb-976f-ef41e0861871.png">

but when I switch to https, the websocket protocol switch from _ws://nodered.mydomain.com/comms_ to _**wss**://nodered.mydomain.com/comms_
 
and status is endless '_pending_' as described at the beginning of this ticket. 

```
[nodered-https]
type = https
custom_domains = nodered.mydomain.com

plugin = https2http
plugin_local_addr = my-server-ip:1880
plugin_crt_path = /etc/fullchain.pem
plugin_key_path = /etc/privkey.pem
plugin_host_header_rewrite = my-server-ip:1880
```

Do you have any idea how to proxy wss protocol thanks to FRP ? 

Thanks ! all the best !

**Comment by dizzam** [comment]
I encounter the same problem when using `https2http` plugin, when the backend is not nginx. I think it might because the backend does not provide as much information as nginx to the frp for it's normally functioning. As suggested by #2125, you could use nginx as an intermediate server to do the http to https convert, like `backend <---http---> nginx <---https---> frp`.

**Comment by yuyulei** [comment]
a websocket bug fixed by #2199 , now you can try new release v0.35.0

wss will be supported later.

> Hello, I digg into this issue and found that websocket are working properly in http mode:
> 
> ```
> [nodered-http]
> type = http
> local_ip = my-server-ip
> local_port = 1880
> custom_domains = nodered.mydomain.com
> ```
> 
> <img alt="ws" width="888" src="https://user-images.githubusercontent.com/3525134/101511554-f4c0c700-397a-11eb-976f-ef41e0861871.png">
> 
> but when I switch to https, the websocket protocol switch from _ws://nodered.mydomain.com/comms_ to _**wss**://nodered.mydomain.com/comms_
> 
> and status is endless '_pending_' as described at the beginning of this ticket.
> 
> ```
> [nodered-https]
> type = https
> custom_domains = nodered.mydomain.com
> 
> plugin = https2http
> plugin_local_addr = my-server-ip:1880
> plugin_crt_path = /etc/fullchain.pem
> plugin_key_path = /etc/privkey.pem
> plugin_host_header_rewrite = my-server-ip:1880
> ```
> 
> Do you have any idea how to proxy wss protocol thanks to FRP ?
> 
> Thanks ! all the best !

**Comment by dizzam** [comment]
I test it in the lastest dev branch and it seems that the problem persists.

I created a [test case](https://github.com/fatedier/frp/files/5851428/wss_test.tar.gz) to reproduce this issue. It seems that it's a different issue from the KeepAlive one, because in the test case, all the requests is simulated in the tcp layer.

```bash
# Ubuntu 20.04
tar zxf wss_test.tar.gz
cd wss_test
frps -c frps.ini &
frpc -c frpc.ini &
```

In another shell
```bash
python3 wss_test.py
# The read operation timed out when client accepting handshaking message
```

Some explanation can be seen in `wss_test.py`.

**Comment by yuyulei** [comment]
I give a  https proxy demo to support wss access.

frps.ini
```
```

> Hello, I digg into this issue and found that websocket are working properly in http mode:
> 
> ```
> [nodered-http]
> type = http
> local_ip = my-server-ip
> local_port = 1880
> custom_domains = nodered.mydomain.com
> ```
> 
> <img alt="ws" width="888" src="https://user-images.githubusercontent.com/3525134/101511554-f4c0c700-397a-11eb-976f-ef41e0861871.png">
> 
> but when I switch to https, the websocket protocol switch from _ws://nodered.mydomain.com/comms_ to _**wss**://nodered.mydomain.com/comms_
> 
> and status is endless '_pending_' as described at the beginning of this ticket.
> 
> ```
> [nodered-https]
> type = https
> custom_domains = nodered.mydomain.com
> 
> plugin = https2http
> plugin_local_addr = my-server-ip:1880
> plugin_crt_path = /etc/fullchain.pem
> plugin_key_path = /etc/privkey.pem
> plugin_host_header_rewrite = my-server-ip:1880
> ```
> 
> Do you have any idea how to proxy wss protocol thanks to FRP ?
> 
> Thanks ! all the best !

@fredericmalo https proxy can support wss. Give a frpc.ini demo if the server can accept **https** request:

```
[nodered-https]
type = https
local_ip = my-server-ip
local_port = 1880
custom_domains = nodered.mydomain.com
```

And make sure that request Host same to OriginHost.

**Comment by yuyulei** [comment]
@dizzam there is some problem in http(s) plugin to support ws(s). Can you use http(s) proxy directly ?
